/*$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: blinky_console.qm
* File:  ${.::blinky.c}
*
* This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky} ...........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
    QTimeEvt buzzerTimeEvt;
    uint8_t buzzerCount;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me, void const * const par);
static QState Blinky_Idle(Blinky * const me, QEvt const * const e);
static QState Blinky_RCWait(Blinky * const me, QEvt const * const e);
static QState Blinky_AutoWait(Blinky * const me, QEvt const * const e);
/*$enddecl${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* instantiate the Blinky active object ------------------------------------*/
static Blinky l_blinky;
QActive * const AO_Blinky = &l_blinky.super;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Blinky_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky_ctor} ......................................................*/
void Blinky_ctor(void) {
    Blinky *me = (Blinky *)AO_Blinky;
    QActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->buzzerTimeEvt, &me->super, PLAY_BUZZER_SIG, 0U);
}
/*$enddef${AOs::Blinky_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky} ...........................................................*/

/*${AOs::Blinky::SM} .......................................................*/
static QState Blinky_initial(Blinky * const me, void const * const par) {
    /*${AOs::Blinky::SM::initial} */
    (void)par; /* unused parameter */
    /* arm the private time event to expire in 1/2s
    * and periodically every 1/2 second
    */
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
    QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);

    me->buzzerCount = 0U;
    return Q_TRAN(&Blinky_Idle);
}

/*${AOs::Blinky::SM::Idle} .................................................*/
static QState Blinky_Idle(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::Idle} */
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            BSP_motorsOff();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::Idle} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::Idle::TIMEOUT} */
        case TIMEOUT_SIG: {
            BSP_ledToggle();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::Idle::START_RC} */
        case START_RC_SIG: {
            status_ = Q_TRAN(&Blinky_RCWait);
            break;
        }
        /*${AOs::Blinky::SM::Idle::START_AUTO} */
        case START_AUTO_SIG: {
            status_ = Q_TRAN(&Blinky_AutoWait);
            break;
        }
        /*${AOs::Blinky::SM::Idle::PLAY_BUZZER} */
        case PLAY_BUZZER_SIG: {
            BSP_ledStrip(me->buzzerCount, 1);
            BSP_buzzer_beep();

            if (me->buzzerCount == 16) {
                QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC, 0);
            } else if (me->buzzerCount < 16){
                QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);
            }


            me->buzzerCount += 1;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::RCWait} ...............................................*/
static QState Blinky_RCWait(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::RCWait} */
        case Q_ENTRY_SIG: {
            BSP_startRC();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::AutoWait} .............................................*/
static QState Blinky_AutoWait(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::AutoWait} */
        case Q_ENTRY_SIG: {
            BSP_startAuto();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef Q_SPY

void blinky_update_qs_dict(){

    QS_OBJ_DICTIONARY(&l_blinky);
    QS_OBJ_DICTIONARY(&l_blinky.timeEvt);
    QS_OBJ_DICTIONARY(&l_blinky.buzzerTimeEvt);

    QS_SIG_DICTIONARY(TIMEOUT_SIG,     (void *)0);
    QS_SIG_DICTIONARY(PLAY_BUZZER_SIG, (void *)0);
    QS_SIG_DICTIONARY(START_RC_SIG,    (void *)0);
    QS_SIG_DICTIONARY(START_AUTO_SIG,  (void *)0);


    QS_FUN_DICTIONARY(&Blinky_Idle);
    QS_FUN_DICTIONARY(&Blinky_AutoWait);
    QS_FUN_DICTIONARY(&Blinky_RCWait);
}

#endif
