#ifndef BSP_GPIO_MAPPING_H
#define BSP_GPIO_MAPPING_H

#include "bsp_gpio.h"

#define BOARD_NUM_DIST_SENSORS  9

// Button
#define GPIO_BUTTON_PIN          IO_PIN_15
#define GPIO_BUTTON_PORT         IO_PORTA

// DIstance Sensors
#define GPIO_DIST_SENSOR_0_PIN   IO_PIN_0      
#define GPIO_DIST_SENSOR_0_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_1_PIN   IO_PIN_1     
#define GPIO_DIST_SENSOR_1_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_2_PIN   IO_PIN_2      
#define GPIO_DIST_SENSOR_2_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_3_PIN   IO_PIN_3      
#define GPIO_DIST_SENSOR_3_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_4_PIN   IO_PIN_4      
#define GPIO_DIST_SENSOR_4_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_5_PIN   IO_PIN_5      
#define GPIO_DIST_SENSOR_5_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_6_PIN   IO_PIN_6      
#define GPIO_DIST_SENSOR_6_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_7_PIN   IO_PIN_7      
#define GPIO_DIST_SENSOR_7_PORT  IO_PORTA      

#define GPIO_DIST_SENSOR_8_PIN   IO_PIN_8      
#define GPIO_DIST_SENSOR_8_PORT  IO_PORTA      

uint8_t gpio_dist_sensor_pins[BOARD_NUM_DIST_SENSORS] = {
    GPIO_DIST_SENSOR_0_PIN,
    GPIO_DIST_SENSOR_1_PIN,
    GPIO_DIST_SENSOR_2_PIN,
    GPIO_DIST_SENSOR_3_PIN,
    GPIO_DIST_SENSOR_4_PIN,
    GPIO_DIST_SENSOR_5_PIN,
    GPIO_DIST_SENSOR_6_PIN,
    GPIO_DIST_SENSOR_7_PIN,
    GPIO_DIST_SENSOR_8_PIN,
};

uint8_t gpio_dist_sensor_ports[BOARD_NUM_DIST_SENSORS] = {
    GPIO_DIST_SENSOR_0_PORT,
    GPIO_DIST_SENSOR_1_PORT,
    GPIO_DIST_SENSOR_2_PORT,
    GPIO_DIST_SENSOR_3_PORT,
    GPIO_DIST_SENSOR_4_PORT,
    GPIO_DIST_SENSOR_5_PORT,
    GPIO_DIST_SENSOR_6_PORT,
    GPIO_DIST_SENSOR_7_PORT,
    GPIO_DIST_SENSOR_8_PORT,
};
#endif /* BSP_GPIO_MAPPING_H */