/*$file${.::src::sumo_hsm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: sumo_hsm.qm
* File:  ${.::src::sumo_hsm.c}
*
* This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #    : QM-EVAL-QPC
* Issued to    : Users of QP/C Real-Time Embedded Framework (RTEF)
* Framework(s) : qpc
* Support ends : 2023-12-31
* License scope:
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is free software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::src::sumo_hsm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include <math.h>
#include "qf_custom_defines.h"
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "bsp_led.h"
#include "bsp_motors.h"
#include "bsp_buzzer.h"
#include "bsp_radio.h"
#include "bsp_dist_sensors.h"

#define CALIB_ANGLE_MULT    2.5
#ifndef M_PI
#define M_PI                3.14159265
#endif
/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::SumoHSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM} ..........................................................*/
typedef struct {
/* protected: */
    QMActive super;

/* private: */
    QTimeEvt timeEvt;
    QTimeEvt buzzerTimeEvt;
    uint8_t buzzerCount;
    uint8_t strategy;
    QTimeEvt timeEvt_2;
    uint32_t calib_time_1;
    uint32_t calib_time_2;
    uint8_t calib_status;
    uint16_t turn_180_time_ms;
    uint8_t star_velocity;

/* private submachines */
    /* exit points for submachine ${AOs::SumoHSM::SM::LineSubmachine} */
    struct SM_LineSubmachine {
        QMState super;
        QActionHandler const XP1; /* eXit-Point segment */
    } const *sub_LineSubmachine;
} SumoHSM;

/* protected: */
static QState SumoHSM_initial(SumoHSM * const me, void const * const par);
static QState SumoHSM_Idle  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_Idle_e(SumoHSM * const me);
static QState SumoHSM_Idle_x(SumoHSM * const me);
static QMState const SumoHSM_Idle_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_Idle),
    Q_ACTION_CAST(&SumoHSM_Idle_e),
    Q_ACTION_CAST(&SumoHSM_Idle_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_RCWait  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_RCWait_e(SumoHSM * const me);
static QState SumoHSM_RCWait_x(SumoHSM * const me);
static QMState const SumoHSM_RCWait_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_RCWait),
    Q_ACTION_CAST(&SumoHSM_RCWait_e),
    Q_ACTION_CAST(&SumoHSM_RCWait_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_StarStrategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_StarStrategy_e(SumoHSM * const me);
static QMState const SumoHSM_StarStrategy_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_StarStrategy),
    Q_ACTION_CAST(&SumoHSM_StarStrategy_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_AutoWait  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_AutoWait_e(SumoHSM * const me);
static QMState const SumoHSM_AutoWait_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_AutoWait),
    Q_ACTION_CAST(&SumoHSM_AutoWait_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_StepsStrategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_StepsStrategy_e(SumoHSM * const me);
static QState SumoHSM_StepsStrategy_x(SumoHSM * const me);
static QMState const SumoHSM_StepsStrategy_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_StepsStrategy),
    Q_ACTION_CAST(&SumoHSM_StepsStrategy_e),
    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibTurn  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibTurn_e(SumoHSM * const me);
static QMState const SumoHSM_CalibTurn_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_CalibTurn),
    Q_ACTION_CAST(&SumoHSM_CalibTurn_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibLineGoBack  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibLineGoBack_e(SumoHSM * const me);
static QMState const SumoHSM_CalibLineGoBack_s = {
    &SumoHSM_CalibTurn_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_CalibLineGoBack),
    Q_ACTION_CAST(&SumoHSM_CalibLineGoBack_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibeLineTurn  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibeLineTurn_e(SumoHSM * const me);
static QMState const SumoHSM_CalibeLineTurn_s = {
    &SumoHSM_CalibLineGoBack_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_CalibeLineTurn),
    Q_ACTION_CAST(&SumoHSM_CalibeLineTurn_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibWait  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibWait_e(SumoHSM * const me);
static QState SumoHSM_CalibWait_x(SumoHSM * const me);
static QMState const SumoHSM_CalibWait_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_CalibWait),
    Q_ACTION_CAST(&SumoHSM_CalibWait_e),
    Q_ACTION_CAST(&SumoHSM_CalibWait_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibFront  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibFront_e(SumoHSM * const me);
static QMState const SumoHSM_CalibFront_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_CalibFront),
    Q_ACTION_CAST(&SumoHSM_CalibFront_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibFrontGoBack  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibFrontGoBack_e(SumoHSM * const me);
static QMState const SumoHSM_CalibFrontGoBack_s = {
    &SumoHSM_CalibFront_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_CalibFrontGoBack),
    Q_ACTION_CAST(&SumoHSM_CalibFrontGoBack_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_CalibeFrontTurn  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_CalibeFrontTurn_e(SumoHSM * const me);
static QMState const SumoHSM_CalibeFrontTurn_s = {
    &SumoHSM_CalibFrontGoBack_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_CalibeFrontTurn),
    Q_ACTION_CAST(&SumoHSM_CalibeFrontTurn_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_RC  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_RC_e(SumoHSM * const me);
static QMState const SumoHSM_RC_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_RC),
    Q_ACTION_CAST(&SumoHSM_RC_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_line1  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_line1_e(SumoHSM * const me);
static QState SumoHSM_line1_XP1(SumoHSM * const me);
static struct SM_LineSubmachine const SumoHSM_line1_s = {
    {
        QM_STATE_NULL, /* superstate (top) */
        Q_STATE_CAST(&SumoHSM_line1),
        Q_ACTION_CAST(&SumoHSM_line1_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&SumoHSM_line1_XP1)
};
static QState SumoHSM_line2  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_line2_e(SumoHSM * const me);
static QState SumoHSM_line2_XP1(SumoHSM * const me);
static struct SM_LineSubmachine const SumoHSM_line2_s = {
    {
        QM_STATE_NULL, /* superstate (top) */
        Q_STATE_CAST(&SumoHSM_line2),
        Q_ACTION_CAST(&SumoHSM_line2_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&SumoHSM_line2_XP1)
};

/* submachine ${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_x(SumoHSM * const me);
static QState SumoHSM_LineSubmachine_i(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_s = {
    QM_STATE_NULL, /* superstate unused */
    Q_STATE_CAST(&SumoHSM_LineSubmachine),
    Q_ACTION_NULL, /* no entry action */
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_x),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i)
};
static QState SumoHSM_LineSubmachine_LineGoBack  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_LineGoBack_e(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_LineGoBack_s = {
    &SumoHSM_LineSubmachine_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_LineSubmachine_LineGoBack),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineGoBack_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_LineSubmachine_LineTurn  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_LineTurn_e(SumoHSM * const me);
static QState SumoHSM_LineSubmachine_LineTurn_x(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_LineTurn_s = {
    &SumoHSM_LineSubmachine_LineGoBack_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_LineSubmachine_LineTurn),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurn_e),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurn_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*$enddecl${AOs::SumoHSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

static void SumoHSM_change_strategy(SumoHSM * const me);

/* instantiate the Blinky active object ------------------------------------*/
static SumoHSM l_sumo_hsm;
QActive * const AO_SumoHSM = &l_sumo_hsm.super.super;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::SumoHSM_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM_ctor} .....................................................*/
void SumoHSM_ctor(void) {
    SumoHSM *me = (SumoHSM *)AO_SumoHSM;
    QMActive_ctor(&me->super, Q_STATE_CAST(&SumoHSM_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super.super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->timeEvt_2, &me->super.super, TIMEOUT_2_SIG, 0U);
    QTimeEvt_ctorX(&me->buzzerTimeEvt, &me->super.super, PLAY_BUZZER_SIG, 0U);
    me->strategy = 0;
    me->calib_time_1 = 0;
    me->calib_time_2 = 0;
    me->calib_status = 0;
    me->turn_180_time_ms = 800;
    me->star_velocity = 60;
}
/*$enddef${AOs::SumoHSM_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

static void SumoHSM_change_strategy(SumoHSM * const me) {
    me->strategy++;
    if (me->strategy > 2){
        me->strategy = 0;
    }
}

/*$define${AOs::SumoHSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM} ..........................................................*/

/*${AOs::SumoHSM::SM} ......................................................*/
static QState SumoHSM_initial(SumoHSM * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_Idle_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_Idle_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*${AOs::SumoHSM::SM::initial} */
    (void)par; /* unused parameter */
    /* arm the private time event to expire in 1/2s
    * and periodically every 1/2 second
    */
    QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);

    me->buzzerCount = 0U;

    QS_FUN_DICTIONARY(&SumoHSM_Idle);
    QS_FUN_DICTIONARY(&SumoHSM_RCWait);
    QS_FUN_DICTIONARY(&SumoHSM_StarStrategy);
    QS_FUN_DICTIONARY(&SumoHSM_AutoWait);
    QS_FUN_DICTIONARY(&SumoHSM_StepsStrategy);
    QS_FUN_DICTIONARY(&SumoHSM_CalibTurn);
    QS_FUN_DICTIONARY(&SumoHSM_CalibLineGoBack);
    QS_FUN_DICTIONARY(&SumoHSM_CalibeLineTurn);
    QS_FUN_DICTIONARY(&SumoHSM_CalibWait);
    QS_FUN_DICTIONARY(&SumoHSM_CalibFront);
    QS_FUN_DICTIONARY(&SumoHSM_CalibFrontGoBack);
    QS_FUN_DICTIONARY(&SumoHSM_CalibeFrontTurn);
    QS_FUN_DICTIONARY(&SumoHSM_RC);
    QS_FUN_DICTIONARY(&SumoHSM_line1);
    QS_FUN_DICTIONARY(&SumoHSM_line2);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine_LineGoBack);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine_LineTurn);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine);

    return QM_TRAN_INIT(&tatbl_);
}

/*${AOs::SumoHSM::SM::Idle} ................................................*/
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle_e(SumoHSM * const me) {
    BSP_ledOff();
    BSP_motors(0,0);
    me->strategy = 0;
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
    return QM_ENTRY(&SumoHSM_Idle_s);
}
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_disarm(&me->buzzerTimeEvt);
    return QM_EXIT(&SumoHSM_Idle_s);
}
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::Idle::TIMEOUT} */
        case TIMEOUT_SIG: {
            BSP_ledToggle();
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::RADIO_EVT_1} */
        case RADIO_EVT_1_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_Idle_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::PLAY_BUZZER} */
        case PLAY_BUZZER_SIG: {
            BSP_buzzerBeep();

            if (me->buzzerCount == 15) {
                QTimeEvt_armX(&me->buzzerTimeEvt, 1.6 * BSP_TICKS_PER_SEC, 0);
                BSP_ledStripe(me->buzzerCount, 0x94, 0x00, 0xD3);
            } else if (me->buzzerCount < 15){
                QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);
                BSP_ledStripe(me->buzzerCount, 0x94, 0x00, 0xD3);
            }


            me->buzzerCount += 1;
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::RCWait} ..............................................*/
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait_e(SumoHSM * const me) {
    BSP_ledOff();
    BSP_ledStripeSetStrategyColor(me->strategy);
    BSP_motors(0,0);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/10, BSP_TICKS_PER_SEC/10);
    return QM_ENTRY(&SumoHSM_RCWait_s);
}
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    return QM_EXIT(&SumoHSM_RCWait_s);
}
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::RCWait::START} */
        case START_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RC_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_RC_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::RCWait::RADIO_EVT_1} */
        case RADIO_EVT_1_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_CalibWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::RCWait::TIMEOUT} */
        case TIMEOUT_SIG: {
            BSP_ledToggle();
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::RCWait::RADIO_EVT_2} */
        case RADIO_EVT_2_SIG: {
            SumoHSM_change_strategy(me);
            BSP_ledStripeSetStrategyColor(me->strategy);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::StarStrategy} ........................................*/
/*${AOs::SumoHSM::SM::StarStrategy} */
static QState SumoHSM_StarStrategy_e(SumoHSM * const me) {
    BSP_motors(me->star_velocity, me->star_velocity);
    return QM_ENTRY(&SumoHSM_StarStrategy_s);
}
/*${AOs::SumoHSM::SM::StarStrategy} */
static QState SumoHSM_StarStrategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::StarStrategy::LINE_DETECTED} */
        case LINE_DETECTED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_line1_e), /* entry */
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i), /* initial tran. */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StarStrategy::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StarStrategy::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            if (BSP_distSensorIsReading(DIST_SENSOR_R)) {
               BSP_motors(80,-80);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_FR)) {
               BSP_motors(80,0);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_F)) {
               BSP_motors(100,100);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_FL)) {
               BSP_motors(0,80);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_L)) {
               BSP_motors(-80,80);
            } else {
               BSP_motors(60,60);
            }
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::AutoWait} ............................................*/
/*${AOs::SumoHSM::SM::AutoWait} */
static QState SumoHSM_AutoWait_e(SumoHSM * const me) {
    BSP_motors(0,0);
    BSP_ledOn();
    BSP_ledStripeSetStrategyColor(me->strategy);
    return QM_ENTRY(&SumoHSM_AutoWait_s);
}
/*${AOs::SumoHSM::SM::AutoWait} */
static QState SumoHSM_AutoWait(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::AutoWait::START} */
        case START_SIG: {
            /*${AOs::SumoHSM::SM::AutoWait::START::[strategy_0]} */
            if (me->strategy == 0) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_StarStrategy_s, /* target state */
                    {
                        Q_ACTION_CAST(&SumoHSM_StarStrategy_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::AutoWait::START::[strategy_1]} */
            else if (me->strategy == 1) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_StepsStrategy_s, /* target state */
                    {
                        Q_ACTION_CAST(&SumoHSM_StepsStrategy_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        /*${AOs::SumoHSM::SM::AutoWait::RADIO_EVT_1} */
        case RADIO_EVT_1_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RCWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::AutoWait::RADIO_EVT_2} */
        case RADIO_EVT_2_SIG: {
            SumoHSM_change_strategy(me);
            BSP_ledStripeSetStrategyColor(me->strategy);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::StepsStrategy} .......................................*/
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy_e(SumoHSM * const me) {
    QTimeEvt_armX(&me->timeEvt, 3 * BSP_TICKS_PER_SEC, 3 * BSP_TICKS_PER_SEC);
    return QM_ENTRY(&SumoHSM_StepsStrategy_s);
}
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_disarm(&me->timeEvt_2);
    return QM_EXIT(&SumoHSM_StepsStrategy_s);
}
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::StepsStrategy::TIMEOUT} */
        case TIMEOUT_SIG: {
            BSP_motors(100,100);
            QTimeEvt_armX(&me->timeEvt_2, BSP_TICKS_PER_MILISSEC * 100, 0);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::TIMEOUT_2} */
        case TIMEOUT_2_SIG: {
            BSP_motors(0,0);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            QTimeEvt_disarm(&me->timeEvt_2);

            if (BSP_distSensorIsReading(DIST_SENSOR_R)) {
               BSP_motors(80,-80);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_FR)) {
               BSP_motors(80,0);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_F)) {
               BSP_motors(100,100);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_FL)) {
               BSP_motors(0,80);
            } else if (BSP_distSensorIsReading(DIST_SENSOR_L)) {
               BSP_motors(-80,80);
            } else {
               BSP_motors(0,0);
               QTimeEvt_armX(&me->timeEvt, 3 * BSP_TICKS_PER_SEC, 3 * BSP_TICKS_PER_SEC);
            }


            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::LINE_DETECTED} */
        case LINE_DETECTED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_line2_e), /* entry */
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i), /* initial tran. */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibTurn} ...........................................*/
/*${AOs::SumoHSM::SM::CalibTurn} */
static QState SumoHSM_CalibTurn_e(SumoHSM * const me) {
    QTimeEvt_armX(&me->timeEvt_2, 0xFFFFFFFF, 0);
    BSP_motors(me->star_velocity, me->star_velocity);
    return QM_ENTRY(&SumoHSM_CalibTurn_s);
}
/*${AOs::SumoHSM::SM::CalibTurn} */
static QState SumoHSM_CalibTurn(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibTurn::LINE_DETECTED} */
        case LINE_DETECTED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibLineGoBack_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibLineGoBack_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            if (me->calib_status == 0){
                me->calib_time_1 = 0xFFFFFFFF - QTimeEvt_currCtr(&me->timeEvt_2);
            } else {
                me->calib_time_2 = 0xFFFFFFFF - QTimeEvt_currCtr(&me->timeEvt_2);
            }
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack} ..........................*/
/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack} */
static QState SumoHSM_CalibLineGoBack_e(SumoHSM * const me) {
    BSP_motors(-100,-100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 250, 0);
    return QM_ENTRY(&SumoHSM_CalibLineGoBack_s);
}
/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack} */
static QState SumoHSM_CalibLineGoBack(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibeLineTurn_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibeLineTurn_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn} ..........*/
/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn} */
static QState SumoHSM_CalibeLineTurn_e(SumoHSM * const me) {
    BSP_motors(-100,100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * me->turn_180_time_ms, 0);
    return QM_ENTRY(&SumoHSM_CalibeLineTurn_s);
}
/*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn} */
static QState SumoHSM_CalibeLineTurn(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn::TIMEOUT} */
        case TIMEOUT_SIG: {
            /*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn::TIMEOUT::[calib_0]} */
            if (me->calib_status == 0) {
                static QMTranActTable const tatbl_ = { /* tran-action table */
                    &SumoHSM_CalibTurn_s, /* target state */
                    {
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                me->calib_status++;
                QTimeEvt_rearm(&me->timeEvt_2, 0xFFFFFFFF);
                BSP_motors(60,60);

                status_ = QM_TRAN(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::CalibTurn::CalibLineGoBack::CalibeLineTurn::TIMEOUT::[calib_1]} */
            else if (me->calib_status != 0) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_CalibWait_s, /* target state */
                    {
                        Q_ACTION_CAST(&SumoHSM_CalibWait_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                QTimeEvt_disarm(&me->timeEvt_2);

                uint8_t angle_diff;
                if (me->calib_time_2 > me->calib_time_1){
                    angle_diff = 0;
                } else {
                    angle_diff = ((180 / M_PI) * acos((me->calib_time_2) / (double) me->calib_time_1));
                }

                if (me->strategy == 0) {
                    me->turn_180_time_ms += angle_diff * CALIB_ANGLE_MULT;
                } else {
                    me->turn_180_time_ms -= angle_diff * CALIB_ANGLE_MULT;
                }


                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibWait} ...........................................*/
/*${AOs::SumoHSM::SM::CalibWait} */
static QState SumoHSM_CalibWait_e(SumoHSM * const me) {
    BSP_ledOn();
    BSP_motors(0,0);
    BSP_ledStripeSetStrategyColor(me->strategy);
    me->calib_status = 0;
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 250, 0);
    return QM_ENTRY(&SumoHSM_CalibWait_s);
}
/*${AOs::SumoHSM::SM::CalibWait} */
static QState SumoHSM_CalibWait_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    return QM_EXIT(&SumoHSM_CalibWait_s);
}
/*${AOs::SumoHSM::SM::CalibWait} */
static QState SumoHSM_CalibWait(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibWait::START} */
        case START_SIG: {
            /*${AOs::SumoHSM::SM::CalibWait::START::[strategy_0||strategy_1]} */
            if (me->strategy == 0 || me->strategy == 1) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_CalibTurn_s, /* target state */
                    {
                        Q_ACTION_CAST(&SumoHSM_CalibWait_x), /* exit */
                        Q_ACTION_CAST(&SumoHSM_CalibTurn_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::CalibWait::START::[strategy_2]} */
            else if (me->strategy == 2) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_CalibFront_s, /* target state */
                    {
                        Q_ACTION_CAST(&SumoHSM_CalibWait_x), /* exit */
                        Q_ACTION_CAST(&SumoHSM_CalibFront_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        /*${AOs::SumoHSM::SM::CalibWait::RADIO_EVT_1} */
        case RADIO_EVT_1_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_Idle_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibWait_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_Idle_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_ledStripeSetAll(0x94, 0x00, 0xD3);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::CalibWait::TIMEOUT} */
        case TIMEOUT_SIG: {
            static bool time_long;

            BSP_ledToggle();

            if (time_long){
                QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 150, 0);
            } else {
                QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 1000, 0);
            }
            time_long = !time_long;


            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::CalibWait::RADIO_EVT_2} */
        case RADIO_EVT_2_SIG: {
            SumoHSM_change_strategy(me);
            BSP_ledStripeSetStrategyColor(me->strategy);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibFront} ..........................................*/
/*${AOs::SumoHSM::SM::CalibFront} */
static QState SumoHSM_CalibFront_e(SumoHSM * const me) {
    QTimeEvt_armX(&me->timeEvt_2, 0xFFFFFFFF, 0);
    BSP_motors(me->star_velocity, me->star_velocity);
    return QM_ENTRY(&SumoHSM_CalibFront_s);
}
/*${AOs::SumoHSM::SM::CalibFront} */
static QState SumoHSM_CalibFront(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibFront::LINE_DETECTED} */
        case LINE_DETECTED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibFrontGoBack_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibFrontGoBack_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            uint32_t time_until_line = 0xFFFFFFFF - QTimeEvt_currCtr(&me->timeEvt_2);

            int16_t diff_to_reference = time_until_line - 285;

            me->star_velocity += (diff_to_reference / 5);


            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack} ........................*/
/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack} */
static QState SumoHSM_CalibFrontGoBack_e(SumoHSM * const me) {
    BSP_motors(-100,-100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 250, 0);
    return QM_ENTRY(&SumoHSM_CalibFrontGoBack_s);
}
/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack} */
static QState SumoHSM_CalibFrontGoBack(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibeFrontTurn_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibeFrontTurn_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack::CalibeFrontTurn} .......*/
/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack::CalibeFrontTurn} */
static QState SumoHSM_CalibeFrontTurn_e(SumoHSM * const me) {
    BSP_motors(-100,100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * me->turn_180_time_ms, 0);
    return QM_ENTRY(&SumoHSM_CalibeFrontTurn_s);
}
/*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack::CalibeFrontTurn} */
static QState SumoHSM_CalibeFrontTurn(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::CalibFront::CalibFrontGoBack::CalibeFrontTurn::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_CalibWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_CalibWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            QTimeEvt_disarm(&me->timeEvt_2);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::RC} ..................................................*/
/*${AOs::SumoHSM::SM::RC} */
static QState SumoHSM_RC_e(SumoHSM * const me) {
    BSP_ledOff();
    (void)me; /* unused parameter */
    return QM_ENTRY(&SumoHSM_RC_s);
}
/*${AOs::SumoHSM::SM::RC} */
static QState SumoHSM_RC(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::RC::RADIO_DATA} */
        case RADIO_DATA_SIG: {
            int coord_x = BSP_radioGetChannel(RADIO_CH1);
            int coord_y = BSP_radioGetChannel(RADIO_CH2);

            int mot1 = coord_y + coord_x;
            int mot2 = coord_y - coord_x;

            BSP_motors(mot1, mot2);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::RC::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RCWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::line1} ...............................................*/
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1_e(SumoHSM * const me) {
    me->sub_LineSubmachine = &SumoHSM_line1_s; /* attach submachine */
    return QM_ENTRY(&SumoHSM_line1_s.super);
}
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1_XP1(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_StarStrategy_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_StarStrategy_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::line2} ...............................................*/
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2_e(SumoHSM * const me) {
    me->sub_LineSubmachine = &SumoHSM_line2_s; /* attach submachine */
    return QM_ENTRY(&SumoHSM_line2_s.super);
}
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2_XP1(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_StepsStrategy_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_StepsStrategy_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine} ......................................*/
/*${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine_x(SumoHSM * const me) {
    return QM_SM_EXIT(&me->sub_LineSubmachine->super);
}
/*${AOs::SumoHSM::SM::LineSubmachine::initial} */
static QState SumoHSM_LineSubmachine_i(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_LineSubmachine_LineGoBack_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineGoBack_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*${AOs::SumoHSM::SM::LineSubmachine::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER_SUB(&me->sub_LineSubmachine->super);
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} ..........................*/
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} */
static QState SumoHSM_LineSubmachine_LineGoBack_e(SumoHSM * const me) {
    BSP_motors(-100,-100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 250, 0);
    return QM_ENTRY(&SumoHSM_LineSubmachine_LineGoBack_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} */
static QState SumoHSM_LineSubmachine_LineGoBack(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_LineTurn_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurn_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::LineTurn} ................*/
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::LineTurn} */
static QState SumoHSM_LineSubmachine_LineTurn_e(SumoHSM * const me) {
    BSP_motors(-100,100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * me->turn_180_time_ms * (0.6), 0);
    return QM_ENTRY(&SumoHSM_LineSubmachine_LineTurn_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::LineTurn} */
static QState SumoHSM_LineSubmachine_LineTurn_x(SumoHSM * const me) {
    BSP_motors(0,0);
    (void)me; /* unused parameter */
    return QM_EXIT(&SumoHSM_LineSubmachine_LineTurn_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::LineTurn} */
static QState SumoHSM_LineSubmachine_LineTurn(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::LineTurn::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurn_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->XP1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::SumoHSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef Q_SPY

void sumoHSM_update_qs_dict(){

    QS_OBJ_DICTIONARY(&l_sumo_hsm);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.timeEvt);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.timeEvt_2);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.buzzerTimeEvt);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.strategy);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.calib_time_1);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.calib_time_2);

    QS_SIG_DICTIONARY(TIMEOUT_SIG,     (void *)0);
    QS_SIG_DICTIONARY(TIMEOUT_2_SIG, (void *)0);
    QS_SIG_DICTIONARY(PLAY_BUZZER_SIG,    (void *)0);
    QS_SIG_DICTIONARY(START_SIG,  (void *)0);
    QS_SIG_DICTIONARY(RADIO_EVT_1_SIG,  (void *)0);
    QS_SIG_DICTIONARY(RADIO_EVT_2_SIG,  (void *)0);
    QS_SIG_DICTIONARY(STOP_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LINE_DETECTED_SIG,  (void *)0);
    QS_SIG_DICTIONARY(DIST_SENSOR_CHANGE_SIG,  (void *)0);
    QS_SIG_DICTIONARY(RADIO_DATA_SIG,  (void *)0);


}

#endif
